name: web
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_API_KEY: ${{secrets.VITE_API_KEY}}
      VITE_AUTH_DOMAIN: ${{secrets.VITE_AUTH_DOMAIN}}
      VITE_PROJECT_ID: ${{secrets.VITE_PROJECT_ID}}
      VITE_STORAGE_BUCKET: ${{secrets.VITE_STORAGE_BUCKET}}
      VITE_MESSAGING_SENDER_ID: ${{secrets.VITE_MESSAGING_SENDER_ID}}
      VITE_APP_ID: ${{secrets.VITE_APP_ID}}
      VITE_MEASUREMENT_ID: ${{secrets.VITE_MEASUREMENT_ID}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Yarn
        run: npm install --location=global yarn

      - name: Install dependencies
        run: yarn

      - name: Build src
        run: yarn build
